### ISSUE TITLE
Generate fails due to character issue

### ISSUE THREAD

**Issue by RichardLitt** [andrew/PBOM#4]
I tried to run this on https://github.com/ProjectBabbler/ebird-api:

```
➜  pbom git:(main) exe/cli.rb generate --input ../ebird-api ../test/.
Generating a new PBOM...
Looking up pkg:pypi/black@24.10.0...
Downloading CITATION.cff from psf/black...
Looking up pkg:pypi/build@1.2.2.post1...
Looking up pkg:pypi/bump2version@1.0.1...
Looking up pkg:pypi/cachetools@5.5.0...
Looking up pkg:pypi/certifi@2024.8.30...
Looking up pkg:pypi/cffi@1.17.1...
Looking up pkg:pypi/chardet@5.2.0...
Looking up pkg:pypi/charset-normalizer@3.3.2...
Looking up pkg:pypi/click@8.1.7...
Looking up pkg:pypi/colorama@0.4.6...
Looking up pkg:pypi/coverage@7.6.1...
Downloading CITATION.cff from nedbat/coveragepy...
Looking up pkg:pypi/cryptography@43.0.1...
Looking up pkg:pypi/distlib@0.3.8...
Looking up pkg:pypi/docutils@0.21.2...
Looking up pkg:pypi/filelock@3.16.1...
Looking up pkg:pypi/flake8@7.1.1...
Looking up pkg:pypi/idna@3.10...
Looking up pkg:pypi/importlib-metadata@8.5.0...
Looking up pkg:pypi/iniconfig@2.0.0...
Looking up pkg:pypi/isort@5.13.2...
Looking up pkg:pypi/jaraco-classes@3.4.0...
Looking up pkg:pypi/jaraco-context@6.0.1...
Looking up pkg:pypi/jaraco-functools@4.1.0...
Looking up pkg:pypi/jeepney@0.8.0...
Looking up pkg:pypi/keyring@25.4.1...
Looking up pkg:pypi/markdown-it-py@3.0.0...
Looking up pkg:pypi/mccabe@0.7.0...
Looking up pkg:pypi/mdurl@0.1.2...
Looking up pkg:pypi/more-itertools@10.5.0...
Looking up pkg:pypi/mypy-extensions@1.0.0...
Looking up pkg:pypi/nh3@0.2.18...
Looking up pkg:pypi/packaging@24.1...
Looking up pkg:pypi/pathspec@0.12.1...
Looking up pkg:pypi/pkginfo@1.10.0...
Looking up pkg:pypi/platformdirs@4.3.6...
Looking up pkg:pypi/pluggy@1.5.0...
Looking up pkg:pypi/pycodestyle@2.12.1...
Looking up pkg:pypi/pycparser@2.22...
Looking up pkg:pypi/pyflakes@3.2.0...
Looking up pkg:pypi/pygments@2.18.0...
Looking up pkg:pypi/pyproject-api@1.8.0...
Looking up pkg:pypi/pyproject-hooks@1.2.0...
Looking up pkg:pypi/pytest@8.3.3...
Downloading CITATION from pytest-dev/pytest...
Looking up pkg:pypi/pytest-cov@5.0.0...
Looking up pkg:pypi/pywin32-ctypes@0.2.3...
Looking up pkg:pypi/readme-renderer@44.0...
Looking up pkg:pypi/requests@2.32.3...
Looking up pkg:pypi/requests-toolbelt@1.0.0...
Looking up pkg:pypi/rfc3986@2.0.0...
Looking up pkg:pypi/rich@13.9.2...
Looking up pkg:pypi/secretstorage@3.3.3...
Looking up pkg:pypi/tox@4.21.2...
Looking up pkg:pypi/twine@5.1.1...
Looking up pkg:pypi/urllib3@2.2.3...
Looking up pkg:pypi/virtualenv@20.26.6...
Looking up pkg:pypi/zipp@3.20.2...
/Users/richard/.rvm/gems/ruby-3.0.0/gems/psych-5.1.2/lib/psych/parser.rb:62:in `_native_parse': (<unknown>): found character that cannot start any token while scanning for the next token at line 2 column 20 (Psych::SyntaxError)
	from /Users/richard/.rvm/gems/ruby-3.0.0/gems/psych-5.1.2/lib/psych/parser.rb:62:in `parse'
	from /Users/richard/.rvm/gems/ruby-3.0.0/gems/psych-5.1.2/lib/psych.rb:455:in `parse_stream'
	from /Users/richard/.rvm/gems/ruby-3.0.0/gems/psych-5.1.2/lib/psych.rb:399:in `parse'
	from /Users/richard/.rvm/gems/ruby-3.0.0/gems/psych-5.1.2/lib/psych.rb:323:in `safe_load'
	from /Users/richard/.rvm/gems/ruby-3.0.0/gems/cff-1.2.0/lib/cff/index.rb:103:in `read'
	from /Users/richard/src/PBOM/lib/pbom/package.rb:100:in `render_citation_cff'
	from /Users/richard/src/PBOM/lib/pbom/package.rb:105:in `generate_bib_entry'
	from /Users/richard/src/PBOM/lib/pbom.rb:59:in `block (2 levels) in generate_references_bib'
	from /Users/richard/src/PBOM/lib/pbom.rb:58:in `each'
	from /Users/richard/src/PBOM/lib/pbom.rb:58:in `block in generate_references_bib'
	from /Users/richard/src/PBOM/lib/pbom.rb:57:in `open'
	from /Users/richard/src/PBOM/lib/pbom.rb:57:in `generate_references_bib'
	from /Users/richard/src/PBOM/lib/pbom.rb:24:in `generate'
	from exe/cli.rb:31:in `<main>'
```

Not sure what's up with that. Will dig.

**Comment by andrew** [comment]
Fixed in https://github.com/andrew/PBOM/commit/8fd116adee0cb3e45c0067f4e440b9e652e3c0de
